#!/usr/bin/env ruby
# mdstyle -- Christian Koch <cfkoch@sdf.lonestar.org>
require 'rubygems'
require 'rdiscount'

infile_path = ARGV.shift

if !infile_path
  warn("usage: mdstyle file")
  exit 1
end

infile = File.read(infile_path).split(/\n-{3,}\n/)
style = infile.first
content = infile.last
content_rendered = RDiscount.new(content, :smart).to_html

$stdout.puts <<-EOF
<!doctype html>

<html lang="en">
<head>
  <meta charset="iso8859-1"/> 
  <style type="text/css">
    #{style}
  </style>
</head>
<body>

#{content_rendered}
  
</body>
</html>
EOF
