#!/usr/bin/env ruby
# mdstyle -- Charlotte Koch <cfkoch@edgebsd.org>
require 'rubygems'
require 'rdiscount'

infile_path = ARGV.shift
infile = nil

if infile_path
  infile = File.read(infile_path)
else
  infile = $stdin.read
end

split = infile.split(/\n\!{3,}\n/)
style = split.first
content = split.last
content_rendered = RDiscount.new(content, :smart).to_html

$stdout.puts <<-EOF
<!doctype html>

<html lang="en">
<head>
  <meta charset="iso8859-1"/> 
  <style type="text/css">
    #{style}
  </style>
</head>
<body>

#{content_rendered}
  
</body>
</html>
EOF
